# Additional services for data analysis
# Run with: docker-compose -f docker-compose.yml -f docker-compose.grafana.yml up -d

services:
  grafana:
    image: grafana/grafana:latest
    container_name: arbitrage-grafana
    restart: unless-stopped
    ports:
      - "${GRAFANA_PORT:-3000}:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin123}
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
      - GF_ANALYTICS_REPORTING_ENABLED=false
      - GF_ANALYTICS_CHECK_FOR_UPDATES=false
      - DATABASE_NAME=${DATABASE_NAME:-arbitrage}
      - DATABASE_USER=${DATABASE_USER:-arbitrage_user}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:-arbitrage_pass}
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
    networks:
      - arbitrage-net
    depends_on:
      timescaledb:
        condition: service_healthy

volumes:
  grafana_data:

networks:
  arbitrage-net:
    external: false