services:
  timescaledb:
    image: timescale/timescaledb:2.16.1-pg16
    container_name: arbitrage-timescaledb
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${DATABASE_NAME:-arbitrage}
      - POSTGRES_USER=${DATABASE_USER:-arbitrage_user}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-arbitrage_pass}
      - TS_TUNE_MEMORY=2GB
      - TS_TUNE_NUM_CPUS=2
    ports:
      - "${DATABASE_PORT:-5433}:5432"
    volumes:
      - timescale_data:/var/lib/postgresql/data
      - ../../database/schemas/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - arbitrage-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER:-arbitrage_user} -d ${DATABASE_NAME:-arbitrage}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  arbitrage-monitor:
    build: ../..
    container_name: arbitrage-monitor
    restart: unless-stopped
    depends_on:
      timescaledb:
        condition: service_healthy
    environment:
      - PYTHONUNBUFFERED=1
      # Core monitoring settings
      - MIN_PROFIT_PERCENTAGE=${MIN_PROFIT_PERCENTAGE:-0.1}
      # Trading fee configuration
      - KRAKEN_TRADING_FEE=${KRAKEN_TRADING_FEE:-0.26}
      - COINMATE_TRADING_FEE=${COINMATE_TRADING_FEE:-0.35}
      - DEFAULT_TRADING_FEE=${DEFAULT_TRADING_FEE:-0.25}
      - DYNAMIC_FEES_ENABLED=${DYNAMIC_FEES_ENABLED:-false}
      # Exchange API keys (optional)
      - KRAKEN_API_KEY=${KRAKEN_API_KEY:-}
      - KRAKEN_SECRET_KEY=${KRAKEN_SECRET_KEY:-}
      - COINMATE_API_KEY=${COINMATE_API_KEY:-}
      - COINMATE_SECRET_KEY=${COINMATE_SECRET_KEY:-}
      - COINMATE_CLIENT_ID=${COINMATE_CLIENT_ID:-}
      # Telegram notifications
      - TELEGRAM_ENABLED=${TELEGRAM_ENABLED:-true}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN:-}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID:-}
      # Database configuration
      - DATABASE_ENABLED=${DATABASE_ENABLED:-true}
      - DATABASE_HOST=timescaledb
      - DATABASE_PORT=5432
      - DATABASE_NAME=${DATABASE_NAME:-arbitrage}
      - DATABASE_USER=${DATABASE_USER:-arbitrage_user}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:-arbitrage_pass}
      - DATABASE_URL=postgresql://${DATABASE_USER:-arbitrage_user}:${DATABASE_PASSWORD:-arbitrage_pass}@timescaledb:5432/${DATABASE_NAME:-arbitrage}
      - DB_RETENTION_DAYS=${DB_RETENTION_DAYS:-30}
      - TIMEZONE=${TIMEZONE:-UTC}
      # Development settings
      - SANDBOX_MODE=${SANDBOX_MODE:-false}
    volumes:
      - ../../logs:/app/logs
      - ../../.env:/app/.env:ro
    networks:
      - arbitrage-net
    healthcheck:
      test: ["CMD", "uv", "run", "python", "-c", "import sys; sys.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  arbitrage-net:
    driver: bridge

volumes:
  timescale_data: