apiVersion: 1

datasources:
  - name: TimescaleDB
    type: postgres
    uid: timescaledb
    url: timescaledb:5432
    database: ${DATABASE_NAME}
    user: ${DATABASE_USER}
    secureJsonData:
      password: ${DATABASE_PASSWORD}
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: true
      searchPath: public
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
    isDefault: true